home:
    path: /
    defaults: { _controller: AppBundle:Home:home }

login:
    path: /login
    defaults: { _controller: AppBundle:Profile:login }
    methods: [GET, POST]

register:
    path: /register
    defaults: { _controller: AppBundle:Profile:register }
    methods: POST

about:
    path: /about

faq:
    path: /faq

contact:
    path: /contact
