home:
    path: /
    defaults: { _controller: AppBundle:Page:home }
    methods: [GET]

order:
    path: /order
    defaults: { _controller: AppBundle:Page:order }
    methods: [GET]

about:
    path: /about

faq:
    path: /faq

contact:
    path: /contact

login:
    path: /login
    defaults: { _controller: AppBundle:Profile:login }
    methods: [GET, POST]

logout:
    path: /logout
    defaults: { _controller: AppBundle:Profile:logout }
    methods: [GET]

register:
    path: /register
    defaults: { _controller: AppBundle:Profile:register }
    methods: [POST]

# api
email_is_unique:
    path: /api/unique-email
    defaults: { _controller: AppBundle:Profile:isUnique }
    methods: [POST]
