services:
    mardizza.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    mardizza.user:
        class: AppBundle\Entity\User

    mardizza.recaptcha_service:
        class: AppBundle\Service\ReCaptchaService
        arguments: ['%recaptcha_private%']
